services:

  mysql:
    image: mysql:8.0
    container_name: gestion-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 30

  backend:
    build: ./backend
    image: ${DOCKERHUB_USER:-local}/gestion-backend:latest
    container_name: gestion-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - app-network

  frontend:
    build: ./frontend
    image: ${DOCKERHUB_USER:-local}/gestion-frontend:latest
    container_name: gestion-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
